// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbZbIBc8AXqTlyWW0_Edl2-fpUHUVhXVU',
    appId: '1:850743178434:web:dbe60353458d11b8e2f75b',
    messagingSenderId: '850743178434',
    projectId: 'complaint-box-6fb15',
    authDomain: 'complaint-box-6fb15.firebaseapp.com',
    storageBucket: 'complaint-box-6fb15.firebasestorage.app',
    measurementId: 'G-BVM35QC3XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW2Y2eGKEESV3YxInmgk-OEmrzzpO1_os',
    appId: '1:850743178434:android:676ac5a7f6766787e2f75b',
    messagingSenderId: '850743178434',
    projectId: 'complaint-box-6fb15',
    storageBucket: 'complaint-box-6fb15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF61_zkBAK90fRzBDFx3qxKvaEkEj5ueE',
    appId: '1:850743178434:ios:c96819ce9d81e8ece2f75b',
    messagingSenderId: '850743178434',
    projectId: 'complaint-box-6fb15',
    storageBucket: 'complaint-box-6fb15.firebasestorage.app',
    androidClientId: '850743178434-ikc1g0af1bdiiiergra0ufb6vvacrnlk.apps.googleusercontent.com',
    iosClientId: '850743178434-islhfu4cu7qbfptj4uohgts2kmq4tdre.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF61_zkBAK90fRzBDFx3qxKvaEkEj5ueE',
    appId: '1:850743178434:ios:c96819ce9d81e8ece2f75b',
    messagingSenderId: '850743178434',
    projectId: 'complaint-box-6fb15',
    storageBucket: 'complaint-box-6fb15.firebasestorage.app',
    androidClientId: '850743178434-ikc1g0af1bdiiiergra0ufb6vvacrnlk.apps.googleusercontent.com',
    iosClientId: '850743178434-islhfu4cu7qbfptj4uohgts2kmq4tdre.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbZbIBc8AXqTlyWW0_Edl2-fpUHUVhXVU',
    appId: '1:850743178434:web:6e4b9cab15adddb0e2f75b',
    messagingSenderId: '850743178434',
    projectId: 'complaint-box-6fb15',
    authDomain: 'complaint-box-6fb15.firebaseapp.com',
    storageBucket: 'complaint-box-6fb15.firebasestorage.app',
    measurementId: 'G-G7SPTZZNFX',
  );
}
